apiVersion: v1
kind: deployment
metadata:
  name: frontend-deploy
  labels:
    app: flask-app
  namespace: project-namespace
spec:
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
spec:
  replicas: 3
  containers:
  - name: flask-app-frontend
    image: zonaira/frontend:latest
    ports:
    - containerPort: 5000

  

