apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: flask-app
  namespace: project-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: flask-app-backend
        image: zonaira/backend:latest
        ports:
        - containerPort: 5001