version: "3.7"
services:
    zonaira-backend:
        container_name: flask-app-backend
        build: ./docker/backend
        image: zonaira/backend:latest
        restart: always
        environment:
          DATABASE_URI: mysql+pymysql://root:password@project-jenkins-db.caumzfitbrs7.eu-west-1.rds.amazonaws.com:3306/jenkins_db
          SECRET_KEY: zonairaisthebest
        ports:
        - target: 5001
          published: 5001

    zonaira-frontend:
        container_name: flask-app-frontend
        build: ./docker/frontend
        image: zonaira/frontend:latest
        restart: always
        ports:
        - target: 5000
          published: 5000



