apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: flask-app
  namespace: project-namespace
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: frontend-service