apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: flask-app
  namespace: project-namespace
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: backend-service

