apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: project-namespace
  labels:
    app: flask-app
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer