ansible-user:
  hosts:
    54.75.83.226:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

test-user:
  hosts:
    34.245.88.183:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'