ansible-user:
  hosts:
    34.248.99.245:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

test-user:
  hosts:
    52.30.124.179:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'